### ISSUE TITLE
0.8/1.0 support

### ISSUE THREAD

**Issue by sfairgrieve** [humangeo/leaflet-tilefilter#1]
Make sure this works with 0.8-dev/1.0 (upcoming)

**Comment by sfairgrieve** [comment]
This is a work in progress.  Check out the 1.0dev branch

**Comment by inessousacaldas** [comment]
Using the plugin from the 1.0dev branch, when I try to use the canvas or css filter it says 'ctx.drawImage is not a function' (line 383). How can I fix this?
